In [3]:
import numpy as np

## The Basics

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([4.0,5.0,6.0])
print(b)

[4. 5. 6.]


In [6]:
# Get Dimension
a.ndim

1

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
# Get Type
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

In [10]:
a.size

3

In [11]:
# Size in bits
a.itemsize

8

In [12]:
a.nbytes

24

## Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Dimension = 2x7
a.shape

(2, 7)

In [16]:
# Get Specific Element = [row, column]
a[1,5]

np.int64(13)

In [17]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Get specific row
a[:, 2]

array([ 3, 10])

In [19]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### 3D 

In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
b.shape

(2, 2, 2)

In [25]:
b.ndim

3

In [26]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [27]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [28]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [ ]:
# All zeroes matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# All ones matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [31]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number also using (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [33]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[5.21676926e-01, 1.19663468e-01, 3.59874638e-01],
        [7.25499467e-01, 2.27546766e-01, 9.09471450e-01]],

       [[3.71372414e-01, 7.86374587e-01, 4.72656197e-01],
        [9.05827290e-01, 6.30178419e-01, 4.14255178e-01]],

       [[7.19392741e-01, 6.84952425e-02, 9.98918632e-01],
        [8.19024595e-04, 6.35244166e-01, 6.17487175e-02]],

       [[8.75110101e-02, 8.10123201e-01, 9.29927311e-01],
        [6.26303448e-01, 3.08994258e-01, 5.31835110e-01]]])

In [34]:
# Random integers numbers
np.random.randint(7, size=(3,3))

array([[3, 3, 1],
       [4, 5, 5],
       [4, 6, 6]], dtype=int32)

In [42]:
np.random.randint(4,7, size=(3,3))

array([[4, 6, 4],
       [6, 5, 4],
       [6, 5, 6]], dtype=int32)

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
print(arr,"\n","----------")

r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]] 
 ----------
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
output = np.ones((5,5), dtype='int32')
print(output)

z = np.zeros((3,3), dtype='int32')
z[1,1] = 9
print(z)

print("\n","--------------")

output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]

 --------------
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Be Careful when copying arrays

In [57]:
a = np.array([1,2,3])
b=a
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[100   2   3]


In [58]:
a = np.array([1,2,3])
b=a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


## Mathematics

In [59]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [60]:
a+2

array([3, 4, 5, 6])

In [61]:
a-2

array([-1,  0,  1,  2])

In [62]:
a*2

array([2, 4, 6, 8])

In [63]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [64]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [65]:
a**2

array([ 1,  4,  9, 16])

In [66]:
# Take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear Algebra

In [70]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Statistics

In [72]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [76]:
np.min(stats)

np.int64(1)

In [77]:
np.max(stats)

np.int64(6)

In [73]:
np.min(stats, axis=1)

array([1, 4])

In [75]:
np.max(stats, axis=1)

array([3, 6])

In [78]:
np.sum(stats)

np.int64(21)

## Reorganising Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
# before.shape
# before.size

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [84]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
# Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])